server:
  port: 8889

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/spring-cloud-training/git-config
security:
  user:
    password: password
encrypt:
  key: springcloud
management:
  security:
    enabled: false